# Generated by Django 3.2.7 on 2023-04-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('number', models.PositiveIntegerField(default=1)),
                ('address', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(default=1)),
                ('teacher_name', models.CharField(max_length=127)),
                ('student_amount', models.PositiveIntegerField(default=1)),
                ('grade', models.CharField(max_length=127)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
