# Generated by Django 3.2.7 on 2023-04-25 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(default=7)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.clas')),
            ],
        ),
    ]
