# Generated by Django 3.2.7 on 2023-04-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230425_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='mainapp.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mainapp.clas'),
        ),
    ]
